### PR TITLE
[FIX] Manager

### PR DESCRIPTION
**Pull request by stevenzeiler**
Fix the broken manager that runs contracts
No longer require payment for contracts, since payment / amortisation didn't quite work anyway.

### CODE REVIEW

**Comment by wilsonianb** [comment]
I'm getting the following error when attempting to run an instance:
```
Possibly unhandled TypeError: Cannot read property 'lastChargedTime' of undefined
    at Manager.calculateCharge (/home/brandon/codius/codius-host/lib/manager.js:184:38)
```

**Comment by stevenzeiler** [comment]
Should the `manager` even be calling `calculateCharge` anymore?

**Comment by wilsonianb** [comment]
That issue goes away if I put `startPollingRunningInstances` behind a billing feature flag
https://github.com/stevenzeiler/codius-host/blob/fix/manager/lib/manager.js#L51

But then I get:
```
Possibly unhandled TypeError: Object #<Object> has no method 'getPortListener'
    at null.<anonymous> (/home/brandon/codius/codius-host/lib/manager.js:117:29)
```

**Comment by stevenzeiler** [comment]
Ah yes I get that error as well. `getPortListener` is a member of `ContractRunner` in codius-engine.

**Comment by wilsonianb** [comment]
Contracts now run. LGTM

**Pull request merged**
