### PR TITLE
Feature/amortizer

### PR DESCRIPTION
**Pull request by wilsonianb**
- Start running instance when balance is credited (instead of at upload)
- Make amortization more accurate by listening for credits and debits
- Return real-time balance with contract metadata
- Turn on amortizer and billing service by default

### CODE REVIEW

**Comment by tdfischer** [comment]
Can you rebase this on top of master to make sure tests pass?

**Comment by wilsonianb** [comment]
Says it's up-to-date.
Some my changes may have affected that failing test. I'll look into it.

**Comment by tdfischer** [comment]
LGTM :+1:

**Comment by wilsonianb** [comment]
+r

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* tdfischer

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
