### PR TITLE
[TEST] Token generation and metadata endpoints

### PR DESCRIPTION
**Pull request by wilsonianb**

### CODE REVIEW

**Comment by stevenzeiler** [comment]
Sweet LGTM

**Comment by stevenzeiler** [comment]
Let's add Travis CI so our shiny new tests can run on all pull requests.

**Comment by codius-montecarlo** [comment]
I see 1 +1s from . Ready to merge.

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
