### PR TITLE
[TASK] Update default cpu prices

### PR DESCRIPTION
**Pull request by wilsonianb**
~$0.02/hour
Operate in xrp instead of drops
[Finishes #89727108]

### CODE REVIEW

**Comment by wilsonianb** [comment]
+r

**Comment by stevenzeiler** [comment]
LGTM

**Comment by stevenzeiler** [comment]
:+1:

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 2 +1s from the following folks:

* stevenzeiler* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
