### PR TITLE
[FIX] Do not delete files of terminated apps

### PR DESCRIPTION
**Pull request by wilsonianb**
TODO: File deletion needs to first check if file is used in other running instances

### CODE REVIEW

**Comment by stevenzeiler** [comment]
LGTM !

**Comment by stevenzeiler** [comment]
:+1:

**Comment by wilsonianb** [comment]
+r

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 2 +1s from the following folks:

* stevenzeiler* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
