### PR TITLE
[DOC] Update README with dependencies & features

### PR DESCRIPTION
**Pull request by wilsonianb**
Rename BILLING_BITCOIND to BITCOIN_BILLING
[Finishes #89637286]

### CODE REVIEW

**Comment by wilsonianb** [comment]
+r

**Comment by stevenzeiler** [comment]
:+1:

**Comment by stevenzeiler** [comment]
LGMT

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 2 +1s from the following folks:

* stevenzeiler* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 2 +1s from the following folks:

* stevenzeiler* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
