### PR TITLE
Test/compute service

### PR DESCRIPTION
**Pull request by wilsonianb**
Depends on https://github.com/codius/codius-host/pull/30

### CODE REVIEW

**Comment by wilsonianb** [comment]
New tests are failing on Travis due to known bug:
https://www.pivotaltracker.com/story/show/87575384

**Comment by stevenzeiler** [comment]
LGTM

**Comment by tdfischer** [comment]
+r

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
