### PR TITLE
Feature/billing service

### PR DESCRIPTION
**Pull request by stevenzeiler**

### CODE REVIEW

**Comment by wilsonianb** [comment]
Tests passed for me. I think lib/billing_service.js line 31 is the only issue.

**Comment by stevenzeiler** [comment]
Thanks Brandon! I will update lib/billing_service.js:31

**Comment by emschwartz** [comment]
LGTM

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* emschwartz

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
