### PR TITLE
[TEST] Add Travis CI

### PR DESCRIPTION
**Pull request by wilsonianb**

### CODE REVIEW

**Comment by tdfischer** [comment]
LGTM :+1:

**Comment by stevenzeiler** [comment]
LGTM

**Comment by codius-montecarlo** [comment]
I see 2 +1s from , . Ready to merge.

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 2 +1s from the following folks:

* tdfischer* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
