### PR TITLE
Feature/compute service

### PR DESCRIPTION
**Pull request by wilsonianb**

### CODE REVIEW

**Comment by wilsonianb** [comment]
Probably not ready to be merged

**Comment by stevenzeiler** [comment]
Do we want to trial this feature behind a `featrure flag`?

**Comment by stevenzeiler** [comment]
If we do a feature flag then we can merge the code without alterning any current behavior, over time transitioning from the current implementation to the Compute Service abstraction.

**Comment by tdfischer** [comment]
+1 for feature flags

**Comment by wilsonianb** [comment]
compute-service itself is behind a feature flag:
https://github.com/codius/codius-host/blob/c37a8d58f47075a64baac459bb1784a645ef7d1c/processes/compute_service.js#L4

I can add calls to the compute-service and put them behind the `COMPUTE_SERVICE` flag.

**Comment by stevenzeiler** [comment]
Oh great thanks Brandon. Whenever we decide to implement calls to the Compute Service we definitely want to use feature flags. In the mean time the pull request LGTM !

**Comment by wilsonianb** [comment]
I've tacked on another commit that needs review. Thanks

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
